pipeline {
    agent any

    environment {
        REGISTRY = 'andersgr'
        IMAGE_NAME = 'env-image'
        DOCKER_CREDENTIALS_ID = 'docker-hub-credentials'
    }

    // Define app as a script variable
    def app

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }
        stage('Test') {
            agent {
                docker { image 'envdev:latest' }
            }
            steps {
                sh 'pytest --cov=app tests/'
            }
        }
        stage('Build Docker Image') {
            steps {
                script {
                    app = docker.build("${REGISTRY}/${IMAGE_NAME}:${env.BUILD_NUMBER}")
                }
            }
        }
        stage('Push Docker Image') {
            when {
                branch 'develop'
            }
            steps {
                script {
                    docker.withRegistry('https://index.docker.io/v1/', DOCKER_CREDENTIALS_ID) {
                        app.push("${env.BUILD_NUMBER}")
                        app.push("latest")
                    }
                }
            }
        }
    }
}
