pipeline {
    agent any
    environment {
         DOCKER_IMAGE = 'envdev:latest'
    }
    stages {
        stage('Checkout from scm') {
            steps {
                checkout scm
            }
        }
        stage('Construir y correr el servicio de prueba') {
            agent {
                docker { image "${DOCKER_IMAGE}" }
            }
            steps {
                sh 'pytest --cov=app tests/'
            }
        }
        stage('Build') {
            when {
                branch 'develop'
            }
            steps {
                echo 'Building the project...'
            }
        }
    }
}